# Form implementation generated from reading ui file 'inquiry.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 750)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inquiry_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.inquiry_widget.setGeometry(QtCore.QRect(240, 70, 341, 571))
        self.inquiry_widget.setStyleSheet("QWidget#inquiry_widget{\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"")
        self.inquiry_widget.setObjectName("inquiry_widget")
        self.inquiry_header = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.inquiry_header.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.inquiry_header.setFont(font)
        self.inquiry_header.setStyleSheet("QLabel#inquiry_header {\n"
"    color: #084924;           /* Dark green text */\n"
"    font-size: 25px;          /* Large font */\n"
"         /* Bold text */\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.inquiry_header.setObjectName("inquiry_header")
        self.label_2 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.push_acad = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.push_acad.setGeometry(QtCore.QRect(10, 80, 151, 41))
        self.push_acad.setStyleSheet("QPushButton#push_acad {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"    \n"
"}\n"
"QPushButton#push_acad:hover {\n"
"    background-color: #e6f3ec;  /* Light green on hover */\n"
"\n"
"}\n"
"QPushButton#push_acad:checked {\n"
"    background-color: #084924;\n"
"    font-weight: bold;\n"
"    color: #084924;\n"
"}\n"
"")
        self.push_acad.setObjectName("push_acad")
        self.push_admin = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.push_admin.setGeometry(QtCore.QRect(10, 130, 151, 41))
        self.push_admin.setStyleSheet("QPushButton#push_admin {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"    \n"
"}\n"
"QPushButton#push_admin:hover {\n"
"    background-color: #e6f3ec;  /* Light green on hover */\n"
"\n"
"}\n"
"QPushButton#push_admin:checked {\n"
"    background-color: #084924;\n"
"    font-weight: bold;\n"
"    color: #084924;\n"
"}\n"
"")
        self.push_admin.setObjectName("push_admin")
        self.push_tech = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.push_tech.setGeometry(QtCore.QRect(170, 80, 161, 41))
        self.push_tech.setStyleSheet("QPushButton#push_tech {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"    \n"
"}\n"
"QPushButton#push_tech:hover {\n"
"    background-color: #e6f3ec;  /* Light green on hover */\n"
"\n"
"}\n"
"QPushButton#push_tech:checked {\n"
"    background-color: #084924;\n"
"    font-weight: bold;\n"
"    color: #084924;\n"
"}\n"
"")
        self.push_tech.setObjectName("push_tech")
        self.push_gen = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.push_gen.setGeometry(QtCore.QRect(170, 130, 161, 41))
        self.push_gen.setStyleSheet("QPushButton#push_gen {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    padding: 8px 12px;\n"
"    font-size: 12px;\n"
"    background-color: white;\n"
"    \n"
"}\n"
"QPushButton#push_gen:hover {\n"
"    background-color: #e6f3ec;  /* Light green on hover */\n"
"\n"
"}\n"
"QPushButton#push_gen:checked {\n"
"    background-color: #084924;\n"
"    font-weight: bold;\n"
"    color: #084924;\n"
"}\n"
"")
        self.push_gen.setObjectName("push_gen")
        self.label_3 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.search_recipt = QtWidgets.QLineEdit(parent=self.inquiry_widget)
        self.search_recipt.setGeometry(QtCore.QRect(20, 210, 301, 22))
        self.search_recipt.setStyleSheet("QLineEdit#search_recipt {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.search_recipt.setObjectName("search_recipt")
        self.label_4 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_5.setGeometry(QtCore.QRect(10, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.search_sub = QtWidgets.QLineEdit(parent=self.inquiry_widget)
        self.search_sub.setGeometry(QtCore.QRect(20, 330, 301, 22))
        self.search_sub.setStyleSheet("QLineEdit#search_sub {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.search_sub.setObjectName("search_sub")
        self.label_6 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_6.setGeometry(QtCore.QRect(10, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.search_msg = QtWidgets.QLineEdit(parent=self.inquiry_widget)
        self.search_msg.setGeometry(QtCore.QRect(20, 390, 301, 22))
        self.search_msg.setStyleSheet("QLineEdit#search_msg {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.search_msg.setObjectName("search_msg")
        self.label_7 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_7.setGeometry(QtCore.QRect(50, 420, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.inquiry_widget)
        self.label_8.setGeometry(QtCore.QRect(10, 440, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.inquiry_widget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 470, 141, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.inquiry_widget)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 490, 161, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.inquiry_widget)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 510, 161, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.button_cancel = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.button_cancel.setGeometry(QtCore.QRect(180, 540, 75, 24))
        self.button_cancel.setStyleSheet("QPushButton#button_cancel{\n"
"    color: #084924;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#button_cancel:hover {\n"
"    background-color: #066838;\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"")
        self.button_cancel.setObjectName("button_cancel")
        self.button_create = QtWidgets.QPushButton(parent=self.inquiry_widget)
        self.button_create.setGeometry(QtCore.QRect(260, 540, 75, 24))
        self.button_create.setStyleSheet("QPushButton#button_create{\n"
"    color: #084924;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton#button_create:hover {\n"
"    background-color: #066838;\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"")
        self.button_create.setObjectName("button_create")
        self.widget = QtWidgets.QWidget(parent=self.inquiry_widget)
        self.widget.setGeometry(QtCore.QRect(20, 270, 301, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inquiry_header.setText(_translate("MainWindow", "New Inquiry"))
        self.label_2.setText(_translate("MainWindow", "Inquiry Type"))
        self.push_acad.setText(_translate("MainWindow", "Academic"))
        self.push_admin.setText(_translate("MainWindow", "Administrative"))
        self.push_tech.setText(_translate("MainWindow", "Technical"))
        self.push_gen.setText(_translate("MainWindow", "General"))
        self.label_3.setText(_translate("MainWindow", "Send to"))
        self.label_4.setText(_translate("MainWindow", "Priority Level"))
        self.label_5.setText(_translate("MainWindow", "Subject"))
        self.label_6.setText(_translate("MainWindow", "Detailed message"))
        self.label_7.setText(_translate("MainWindow", "Be as specific as possible to help us provide the best assistance. "))
        self.label_8.setText(_translate("MainWindow", "Additional Options"))
        self.checkBox_4.setText(_translate("MainWindow", "Request read reciept"))
        self.checkBox_5.setText(_translate("MainWindow", "Send copy to my email"))
        self.checkBox_6.setText(_translate("MainWindow", "Mark as confidential"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
        self.button_create.setText(_translate("MainWindow", "Create"))
        self.checkBox.setText(_translate("MainWindow", "Normal"))
        self.checkBox_2.setText(_translate("MainWindow", "High"))
        self.checkBox_3.setText(_translate("MainWindow", "Urgent"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
