# Form implementation generated from reading ui file 'main_chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon  # Required for setting icons


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 914)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.message_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.message_widget.setGeometry(QtCore.QRect(250, 100, 621, 771))
        self.message_widget.setStyleSheet("QWidget#message_widget {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.message_widget.setObjectName("message_widget")
        self.name_header = QtWidgets.QLabel(parent=self.message_widget)
        self.name_header.setGeometry(QtCore.QRect(80, 10, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.name_header.setFont(font)
        self.name_header.setObjectName("name_header")
        self.header2_accesslvl = QtWidgets.QLabel(parent=self.message_widget)
        self.header2_accesslvl.setGeometry(QtCore.QRect(80, 60, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.header2_accesslvl.setFont(font)
        self.header2_accesslvl.setObjectName("header2_accesslvl")
        self.line_3 = QtWidgets.QFrame(parent=self.message_widget)
        self.line_3.setGeometry(QtCore.QRect(0, 100, 631, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")

        # toolButton with icon (dots.png)
        self.toolButton = QtWidgets.QToolButton(parent=self.message_widget)
        self.toolButton.setGeometry(QtCore.QRect(561, 40, 31, 31))
        self.toolButton.setIcon(QIcon("images/dots.png"))  # Set icon
        self.toolButton.setIconSize(QtCore.QSize(24, 24))  # Icon size
        self.toolButton.setObjectName("toolButton")

        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.message_widget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(600, 110, 16, 651))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.lineedit_msg = QtWidgets.QLineEdit(parent=self.message_widget)
        self.lineedit_msg.setGeometry(QtCore.QRect(100, 710, 451, 31))
        self.lineedit_msg.setStyleSheet("QLineEdit#lineedit_msg {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 10px; /* Slightly smaller radius for a modern, clean look */\n"
"    border: 1px solid #ccc; /* Soft light gray border */\n"
"    padding: 5px 7px; /* Added padding for better spacing */\n"
"    font-size: 14px; /* Adjust font size for readability */\n"
"    color: #333; /* Dark gray text color for readability */\n"
"}\n"
"\n"
"QLineEdit#lineedit_msg:focus {\n"
"    border: 1px solid #084924; /* Blue border when focused (modern feel) */\n"
"    box-shadow: 0 0 5px rgba(76, 158, 255, 0.5); /* Soft shadow effect on focus */\n"
"}\n"
"\n"
"QLineEdit#lineedit_msg:hover {\n"
"    border: 1px solid #888; /* Darker border when hovered */\n"
"    background-color: #e9e9e9; /* Slightly darker background on hover */\n"
"}\n"
"")
        self.lineedit_msg.setObjectName("lineedit_msg")
        self.line_4 = QtWidgets.QFrame(parent=self.message_widget)
        self.line_4.setGeometry(QtCore.QRect(-10, 680, 611, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")

        # Attachments button with icon
        self.button_attachments = QtWidgets.QToolButton(parent=self.message_widget)
        self.button_attachments.setGeometry(QtCore.QRect(10, 710, 31, 31))
        self.button_attachments.setIcon(QIcon("images/open-folder.png"))
        self.button_attachments.setIconSize(QtCore.QSize(24, 24))
        self.button_attachments.setObjectName("button_attachments")

        # Link button with icon
        self.button_link = QtWidgets.QToolButton(parent=self.message_widget)
        self.button_link.setGeometry(QtCore.QRect(50, 710, 31, 31))
        self.button_link.setIcon(QIcon("images/link.png"))
        self.button_link.setIconSize(QtCore.QSize(24, 24))
        self.button_link.setObjectName("button_link")

        # Send button with icon
        self.button_send = QtWidgets.QToolButton(parent=self.message_widget)
        self.button_send.setGeometry(QtCore.QRect(560, 710, 31, 31))
        self.button_send.setIcon(QIcon("images/send.png"))
        self.button_send.setIconSize(QtCore.QSize(24, 24))
        self.button_send.setObjectName("button_send")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_header.setText(_translate("MainWindow", "Person1"))
        self.header2_accesslvl.setText(_translate("MainWindow", "Access "))
        self.toolButton.setText(_translate("MainWindow", ""))  # Removed "..." text
        self.button_attachments.setText(_translate("MainWindow", ""))
        self.button_link.setText(_translate("MainWindow", ""))
        self.button_send.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
