# Form implementation generated from reading ui file 'msg_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 914)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chat_info = QtWidgets.QWidget(parent=self.centralwidget)
        self.chat_info.setGeometry(QtCore.QRect(10, 100, 231, 771))
        self.chat_info.setStyleSheet("QWidget#chat_info {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.chat_info.setObjectName("chat_info")
        self.label_2 = QtWidgets.QLabel(parent=self.chat_info)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.push_edit = QtWidgets.QPushButton(parent=self.chat_info)
        self.push_edit.setGeometry(QtCore.QRect(150, 20, 75, 24))
        self.push_edit.setStyleSheet("QPushButton#push_edit{\n"
"    color: black;                      \n"
"    border: none;                     \n"
"    border-radius: 5px;                        \n"
"    font-size: 14px;                   \n"
"}\n"
"\n"
"QPushButton#push_edit:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#push_edit:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.push_edit.setObjectName("push_edit")
        self.search_recipt = QtWidgets.QLineEdit(parent=self.chat_info)
        self.search_recipt.setGeometry(QtCore.QRect(10, 60, 211, 31))
        self.search_recipt.setStyleSheet("QLineEdit#search_bar {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #cfcfcf;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"")
        self.search_recipt.setObjectName("search_recipt")
        self.line = QtWidgets.QFrame(parent=self.chat_info)
        self.line.setGeometry(QtCore.QRect(0, 90, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.scroll_bar = QtWidgets.QScrollBar(parent=self.chat_info)
        self.scroll_bar.setGeometry(QtCore.QRect(210, 100, 16, 501))
        self.scroll_bar.setStyleSheet("QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 6px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #c0c0c0;\n"
"    border-radius: 3px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"")
        self.scroll_bar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.scroll_bar.setObjectName("scroll_bar")
        self.layoutWidget = QtWidgets.QWidget(parent=self.chat_info)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 201, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_unread = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_unread.setStyleSheet("QPushButton#push_unread{\n"
"    color: black;                      \n"
"    border: none;                     \n"
"    border-radius: 5px;                        \n"
"    font-size: 14px;                   \n"
"}\n"
"\n"
"QPushButton#push_unread:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#push_unread:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.push_unread.setObjectName("push_unread")
        self.horizontalLayout.addWidget(self.push_unread)
        self.push_all = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_all.setStyleSheet("QPushButton#push_all{\n"
"    color: black;                      \n"
"    border: none;                     \n"
"    border-radius: 5px;                        \n"
"    font-size: 14px;                   \n"
"}\n"
"\n"
"QPushButton#push_all:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#push_all:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.push_all.setObjectName("push_all")
        self.horizontalLayout.addWidget(self.push_all)
        self.push_comm = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_comm.setStyleSheet("QPushButton#push_comm{\n"
"    color: black;                      \n"
"    border: none;                     \n"
"    border-radius: 5px;                        \n"
"    font-size: 14px;                   \n"
"}\n"
"\n"
"QPushButton#push_comm:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#push_comm:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.push_comm.setObjectName("push_comm")
        self.horizontalLayout.addWidget(self.push_comm)
        self.push_group = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_group.setStyleSheet("QPushButton#push_group{\n"
"    color: black;                      \n"
"    border: none;                     \n"
"    border-radius: 5px;                        \n"
"    font-size: 14px;                   \n"
"}\n"
"\n"
"QPushButton#push_group:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#push_group:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.push_group.setObjectName("push_group")
        self.horizontalLayout.addWidget(self.push_group)
        self.message_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.message_widget.setGeometry(QtCore.QRect(250, 100, 621, 771))
        self.message_widget.setStyleSheet("QWidget#message_widget {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.message_widget.setObjectName("message_widget")
        self.create_inquiry = QtWidgets.QPushButton(parent=self.message_widget)
        self.create_inquiry.setGeometry(QtCore.QRect(200, 370, 231, 51))
        self.create_inquiry.setStyleSheet("QPushButton#create_inquiry{\n"
"    background-color: #003d1f;          /* Dark green background */\n"
"    color: white;                       /* White text */\n"
"    font-weight: bold;                  /* Bold font */\n"
"    border: none;                       /* No default border */\n"
"    border-radius: 10px;                /* Rounded corners */\n"
"    padding: 8px 20px;                  /* Top/bottom + left/right padding */\n"
"    font-size: 14px;                    /* Slightly larger font */\n"
"}\n"
"\n"
"QPushButton#create_inquiry:hover {\n"
"    background-color: #005a2e;          /* Lighter green on hover */\n"
"}\n"
"\n"
"QPushButton#create_inquiry:pressed {\n"
"    background-color: #002d17;          /* Even darker green when pressed */\n"
"}\n"
"")
        self.create_inquiry.setObjectName("create_inquiry")
        self.label_8 = QtWidgets.QLabel(parent=self.message_widget)
        self.label_8.setGeometry(QtCore.QRect(200, 310, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.contact_info = QtWidgets.QWidget(parent=self.centralwidget)
        self.contact_info.setGeometry(QtCore.QRect(880, 100, 221, 771))
        self.contact_info.setStyleSheet("QWidget#contact_info {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.contact_info.setObjectName("contact_info")
        self.label_9 = QtWidgets.QLabel(parent=self.contact_info)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_2 = QtWidgets.QFrame(parent=self.contact_info)
        self.line_2.setGeometry(QtCore.QRect(0, 60, 221, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.msg_header = QtWidgets.QLabel(parent=self.centralwidget)
        self.msg_header.setGeometry(QtCore.QRect(20, 40, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        self.msg_header.setFont(font)
        self.msg_header.setStyleSheet("QLabel#msg_header {\n"
"    color: #084924;           /* Dark green text */\n"
"    font-size: 25px;          /* Large font */\n"
"    font-weight: bold;        /* Bold text */\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.msg_header.setObjectName("msg_header")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Chats"))
        self.push_edit.setText(_translate("MainWindow", "Edit"))
        self.push_unread.setText(_translate("MainWindow", "Unread"))
        self.push_all.setText(_translate("MainWindow", "All"))
        self.push_comm.setText(_translate("MainWindow", "Comm"))
        self.push_group.setText(_translate("MainWindow", "Group"))
        self.create_inquiry.setText(_translate("MainWindow", "Create a Inquiry"))
        self.label_8.setText(_translate("MainWindow", "No message found!"))
        self.label_9.setText(_translate("MainWindow", "Contact Info"))
        self.msg_header.setText(_translate("MainWindow", "Messaging Center"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
